import 'package:flutter_test/flutter_test.dart';
import 'package:ps_trades_app/models/trade.dart';
import 'package:ps_trades_app/services/excel_export_service.dart';
import 'package:syncfusion_flutter_xlsio/xlsio.dart' as xlsio;

void main() {
  group('ExcelExportService Tests', () {
    const service = ExcelExportService();

    test('generates valid non-empty Excel bytes with 2 sheets for empty trades', () {
      final bytes = service.generateExcelBytes([]);
      expect(bytes, isNotEmpty);

      // Verify that the generated bytes can be loaded back into a Workbook
      final workbook = xlsio.Workbook();
      // syncfusion_flutter_xlsio can create and save, bytes start with PK (zip header)
      // Excel (.xlsx) files are ZIP archives starting with PK (0x50, 0x4B)
      expect(bytes[0], equals(0x50));
      expect(bytes[1], equals(0x4B));
      workbook.dispose();
    });

    test('generates Excel file with trades and monthly summary correctly', () {
      final sampleTrades = [
        Trade(
          id: 't1',
          deviceType: 'PS5 Standard',
          modelCode: 'CFI-1216A',
          serialNumber: 'S01-F55701K7E10927195',
          hasBox: true,
          controllers: 2,
          gamesCount: 3,
          purchaseDate: DateTime(2026, 1, 15),
          purchasePrice: 20000,
          purchasePlatform: 'Facebook',
          sellerNumber: '01011111111',
          sellerLocation: 'Nasr City',
          warrantyMonths: 6,
          gamesIncluded: 'FIFA 24, Spider-Man 2',
          notes: 'Like new condition',
          deviceSellPrice: 24000,
          accessoriesSellPrice: 1000,
          sellingPlatform: 'Marketplace',
          sellDate: DateTime(2026, 1, 25),
          buyerNumber: '01122222222',
          status: TradeStatus.sold,
        ),
        Trade(
          id: 't2',
          deviceType: 'PS5 Slim',
          modelCode: 'CFI-2000',
          serialNumber: 'S02-9988776655',
          hasBox: false,
          controllers: 1,
          gamesCount: 0,
          purchaseDate: DateTime(2026, 2, 10),
          purchasePrice: 22000,
          purchasePlatform: 'OLX',
          sellerNumber: '01233333333',
          sellerLocation: 'Maadi',
          warrantyMonths: 0,
          gamesIncluded: '',
          notes: 'No games included',
          status: TradeStatus.inStock,
        ),
        Trade(
          id: 't3',
          deviceType: 'PS4 Pro',
          modelCode: 'CUH-7216B',
          serialNumber: 'S03-1122334455',
          hasBox: true,
          controllers: 2,
          gamesCount: 5,
          purchaseDate: DateTime(2026, 2, 5),
          purchasePrice: 10000,
          purchasePlatform: 'Telegram',
          sellerNumber: '01544444444',
          sellerLocation: 'Giza',
          warrantyMonths: 3,
          gamesIncluded: 'God of War, GTA V',
          notes: '7216B quiet edition',
          deviceSellPrice: 13500,
          accessoriesSellPrice: 500,
          sellingPlatform: 'OLX',
          sellDate: DateTime(2026, 2, 20),
          buyerNumber: '01099999999',
          status: TradeStatus.sold,
        ),
      ];

      final bytes = service.generateExcelBytes(sampleTrades);
      expect(bytes, isNotEmpty);
      expect(bytes[0], equals(0x50));
      expect(bytes[1], equals(0x4B));
      expect(bytes.length, greaterThan(1000));
    });
  });
}
