name: ps_trades_app
description: تطبيق إدارة تجارة أجهزة PS5 - متابعة الشراء والبيع والأرباح
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Local database
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1

  # State management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Charts
  fl_chart: ^0.66.0

  # Formatting numbers/dates
  intl: ^0.20.2

  # Pick device photos from camera/gallery
  image_picker: ^1.0.7

  # Unique ids
  uuid: ^4.3.3

  # Arabic-friendly fonts
  google_fonts: ^6.1.0

  # Nice icons
  flutter_svg: ^2.0.9

  # Share / export
  share_plus: ^13.3.0
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.10.0
  google_sign_in: ^7.2.0
  http: ^1.6.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
