// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAntO7xcDQ0DMuGXn7iQ2JkzgJLMs1Cqu8',
    appId: '1:224837304509:android:3cb59a85ff99d5136db7d4',
    messagingSenderId: '224837304509',
    projectId: 'playstation-trader',
    storageBucket: 'playstation-trader.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzyFGeq_5RNWdJp_tgHHL1b5zLwVkzFcg',
    appId: '1:224837304509:ios:467ac187c356fe686db7d4',
    messagingSenderId: '224837304509',
    projectId: 'playstation-trader',
    storageBucket: 'playstation-trader.firebasestorage.app',
    androidClientId: '224837304509-c07d20takpe8lcj5onn7h3jbmsosql2b.apps.googleusercontent.com',
    iosClientId: '224837304509-qnrpeehjjle0lmaoq8duvc2h7v662893.apps.googleusercontent.com',
    iosBundleId: 'com.shady.pstrader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXUHaZP6RkGDZPZ7hqX12ep6zCH_hhOHI',
    appId: '1:224837304509:web:ed1fc890ab949e8c6db7d4',
    messagingSenderId: '224837304509',
    projectId: 'playstation-trader',
    authDomain: 'playstation-trader.firebaseapp.com',
    storageBucket: 'playstation-trader.firebasestorage.app',
    measurementId: 'G-2E7KEBY1BZ',
  );
}
